### ISSUE TITLE
Editing Labels as Rich Text 

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/galyleo-dashboard#115]
TypeError: Cannot read properties of undefined (reading 'input')

    at EditPromptModel.TextPromptModel_resolve_ (http://127.0.0.1:9011/lively.components/prompts.cp.js:546:43)
    at EditPromptModel.EditPromptModel_resolve_ (http://127.0.0.1:9011/lively.components/prompts.cp.js:807:139)
    at callOrSetTarget (http://127.0.0.1:9011/lively.bindings/index.js:577:82)
    at AttributeConnection.AttributeConnection_update_ (http://127.0.0.1:9011/lively.bindings/index.js:584:92)
    at Window.signal (http://127.0.0.1:9011/lively.bindings/index.js:93:11)
    at ButtonModel.ButtonModel_trigger_ (http://127.0.0.1:9011/lively.components/buttons.js:137:33)
    at ButtonModel.ButtonModel_handlePressEnd_ (http://127.0.0.1:9011/lively.components/buttons.js:69:22)
    at callOrSetTarget (http://127.0.0.1:9011/lively.bindings/index.js:577:82)
    at AttributeConnection.AttributeConnection_update_ (http://127.0.0.1:9011/lively.bindings/index.js:584:92)
    at Morph.connectionWrapper [as onMouseUp] (http://127.0.0.1:9011/lively.bindings/index.js:683:28)

**Comment by merryman** [comment]
I am pretty sure this will be fixed once we move in the changes that Linus worked on for editing the text morphs.
