### ISSUE TITLE
Infinite Loop in `GalyleoBorderControl`

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/galyleo-dashboard#159]
This is new with the current release of lively.next.  The stack trace is:
```
Error in informMorph: RangeError: Maximum call stack size exceeded
    at LivelyWorld.LivelyWorld_onSubmorphChange_ (world.js:350:26)
    at Window.informMorph (changes.js:24:15)
    at ChangeManager.ChangeManager__record_ (changes.js:400:31)
    at ChangeManager.ChangeManager_addValueChange_ (changes.js:368:27)
    at Morph.Morph_addValueChange_ (morph.js:645:45)
    at Morph.Morph_setProperty_ (morph.js:416:27)
    at Morph.set [as extent] (morph.js:2729:26)
    at Morph.set [as height] (morph.js:2757:40)
    at TilingLayout.TilingLayout_updateContainerViaDom_ (layout.js:1002:36)
    at eval (layout.js:893:24)
```
I believe that the lively people have redone layouts, and this is a possible cause of the error.
Assigning to @merryman for discussion.

```
$world.execCommand("open browser", {moduleName: "studio/controls/border.cp.js", packageName: "galyleo-dashboard", codeEntity: "GalyleoBorderControl"});
```

**Comment by merryman** [comment]
This should be fixed with the most recent update on lively.next.
